#pragma once
#include <stdint.h>
#include <stddef.h>

enum {
    TERMINAL_COLOR_BLACK = 0,
	TERMINAL_COLOR_BLUE = 1,
	TERMINAL_COLOR_GREEN = 2,
	TERMINAL_COLOR_CYAN = 3,
	TERMINAL_COLOR_RED = 4,
	TERMINAL_COLOR_MAGENTA = 5,
	TERMINAL_COLOR_BROWN = 6,
	TERMINAL_COLOR_LIGHT_GRAY = 7,
	TERMINAL_COLOR_DARK_GRAY = 8,
	TERMINAL_COLOR_LIGHT_BLUE = 9,
	TERMINAL_COLOR_LIGHT_GREEN = 10,
	TERMINAL_COLOR_LIGHT_CYAN = 11,
	TERMINAL_COLOR_LIGHT_RED = 12,
	TERMINAL_COLOR_PINK = 13,
	TERMINAL_COLOR_YELLOW = 14,
	TERMINAL_COLOR_WHITE = 15,
};